name: Dockle

on:
  push:
    branches:
      - hotomoe
  pull_request:

jobs:
  dockle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Build an image from Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          provenance: false
          cache-from: type=registry,ref=ghcr.io/hotomoe/hotomoe:hotomoe-buildcache
          tags: |
            misskey:scan
      - name: Run dockle
        uses: docker://goodwithtech/dockle:v0.4.14
        env:
          DOCKLE_OUTPUT_FORMAT: list
          DOCKLE_EXIT_CODE: 1
          DOCKLE_EXIT_LEVEL: WARN
          DOCKLE_IGNORES: CIS-DI-0005,CIS-DI-0010
          DOCKLE_DEBUG: true
        with:
          args: 'misskey:scan'
